---
dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial:
    path: packages/flutter_bluetooth_serial
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  permission_handler: ^12.0.0+1
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.6.0
flutter:
  assets:
    - assets/
  uses-material-design: true
name: noise_mute
publish_to: none
version: 0.1.0